blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/quantumlib/OpenFermion/discussions
    about: Please use GitHub Discussions to ask and answer questions
