blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/quantumlib/OpenFermion/discussions
    about: Use GitHub Discussions to ask and answer questions or start discussions

  - name: Tutorials and references
    url: https://quantumai.google/openfermion/overview
    about: Consult our documentation site for in-depth information about OpenFermion
