#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Dockerfile for OpenFermion, Cirq, and select plugins.

FROM ubuntu:22.04

USER root

WORKDIR /root/workspace
COPY . /root/workspace

# Set PATH for miniforge
ENV PATH="/root/conda/bin:${PATH}"
# Set PATH for pyscf
ENV PYTHONPATH=/root/pyscf

RUN apt-get update && \
    apt-get install -y build-essential \
        bzip2 \
        cmake \
        git \
        wget \
        libblas-dev \
        liblapack-dev \
        curl

# Install miniforge https://github.com/conda-forge/miniforge?tab=readme-ov-file#as-part-of-a-ci-pipeline
RUN wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-aarch64.sh" && \
    bash Miniforge3.sh -b -p "${HOME}/conda" && \
    conda init bash && \
    conda update -n base -c conda-forge conda && \
    # Create virtual env (fermion) with installing Psi4
    conda create -n fermion psi4 python=3.12 -c conda-forge -y && \
    conda install -n fermion pip -y && \
    # Install OpenFermion, Cirq, and plugins
    conda run -n fermion pip install openfermion \ cirq \ openfermioncirq \ openfermionpsi4 \ openfermionpyscf && \
    # Install PySCF
    cd /root && \
    git clone https://github.com/sunqm/pyscf && \
    cd /root/pyscf/pyscf/lib && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make

# Activate venv (fermion)
RUN echo "conda activate fermion" >> ~/.bashrc
