#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Dockerfile for OpenFermion, Cirq, and select plugins.

FROM ubuntu:22.04

USER root

WORKDIR /root/workspace
COPY . /root/workspace

# Set PATH for miniconda
ENV PATH=/root/miniconda3/bin:$PATH
# Set PATH for pyscf
ENV PYTHONPATH=/root/pyscf

RUN apt-get update && \
    apt-get install -y build-essential \
        bzip2 \
        cmake \
        git \
        wget \
        libblas-dev \
        liblapack-dev \
        curl

# Install miniconda for python 3.12, Linux aarch
# https://www.anaconda.com/docs/getting-started/miniconda/install#quickstart-install-instructions
RUN mkdir -p ~/miniconda3 && \
    wget https://repo.anaconda.com/miniconda/Miniconda3-py312_25.5.1-1-Linux-aarch64.sh -O ~/miniconda3/miniconda.sh && \
    bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
    rm ~/miniconda3/miniconda.sh && \
    /bin/bash -c "source ~/miniconda3/bin/activate" && \
    conda init --all && \
    # To accept a channel's Terms of Service
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    # Create virtual env (fermion) with installing Psi4
    conda create -n fermion psi4 python=3.12 -c conda-forge -y && \
    conda install -n fermion pip -y && \
    # Install OpenFermion, Cirq, and plugins
    conda run -n fermion pip install openfermion \ cirq \ openfermioncirq \ openfermionpsi4 \ openfermionpyscf && \
    # Install PySCF
    cd /root && \
    git clone https://github.com/sunqm/pyscf && \
    cd /root/pyscf/pyscf/lib && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make
