# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Zero-configuration modular workflow to run the OSSF Scorecard scanner.
#
# Scorecard (https://github.com/ossf/scorecard) is a repository-scanning tool
# that evaluates a project's security practices. Its use is suggested by
# Google's GitHub team. Scorecard's findings are reported in a repo's scanning
# results page, https://github.com/quantumlib/REPO/security/code-scanning/.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: Scorecard analysis
run-name: Run Scorecard best-practices analyzer ${{inputs.reason}}

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

  # Support merge queues.
  merge_group:
    types:
      - checks_requested

  # Allow manual invocation.
  workflow_dispatch:

  # Allow calling from nightly.yaml.
  workflow_call:
    inputs:
      reason:
        type: string

# Declare default permissions as read only.
permissions: read-all

jobs:
  scorecard:
    name: Run Scorecard analyzer
    runs-on: ubuntu-24.04
    permissions: write-all
    timeout-minutes: 15
    steps:
      - name: Check out a copy of the git repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          # Save the results
          results_file: scorecard-results.sarif
          results_format: sarif

          # Publish results to OpenSSF REST API.
          # See https://github.com/ossf/scorecard-action#publishing-results.
          publish_results: true

      - name: Upload results to code-scanning dashboard
        uses: github/codeql-action/upload-sarif@96f518a34f7a870018057716cc4d7a5c014bd61c # v3
        with:
          sarif_file: scorecard-results.sarif
